runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

PORT: 8080
DB_URL: "mongodb+srv://admin:qwer1234@cluster0.iggptud.mongodb.net/?retryWrites=true&w=majority"
